<a href="https://colab.research.google.com/github/MyDearGreatTeacher/AI4high/blob/master/TF_TensorFlow%E3%81%AE%E7%AC%AC%E4%B8%80%E5%A0%82%E8%AA%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlowの第一堂課

教科書:實戰TensorFlow x Keras工作現場開發

作者： 太田滿久, 須藤広大, 黒澤匠雅, 小田大輔  

譯者： 許郁文

碁峰 出版社

出版日期：2019/03/2

Chapter 3 透過簡單的範例學習 TensorFlow

## 範例一:1+1=2

In [0]:
import tensorflow as tf


a = tf.constant(1, name='a')
b = tf.constant(1, name='b')
c = a + b

with tf.Session() as sess:
    print(sess.run(c))

2


## 範例二:認識Tensorflow  session

In [0]:
import tensorflow as tf


a = tf.constant(1, name='a')
b = tf.constant(1, name='b')
c = a + b

print(c)

Tensor("add_1:0", shape=(), dtype=int32)


In [0]:
import tensorflow as tf


a = tf.constant(1, name='a')
b = tf.constant(1, name='b')
c = a + b

graph = tf.get_default_graph()
print(graph.as_graph_def())

node {
  name: "a"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "b"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "add"
  op: "Add"
  input: "a"
  input: "b"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "a_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "b_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    ke

##常數constant與變數Variable

In [0]:
import tensorflow as tf


a = tf.Variable(1, name='a')
b = tf.constant(1, name='b')
c = tf.assign(a, a + b)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('一回目: [c, a] =', sess.run([c, a]))
    # 変数 c が更新されている
    print('二回目: [c, a] =', sess.run([c, a]))

Instructions for updating:
Colocations handled automatically by placer.
一回目: [c, a] = [2, 2]
二回目: [c, a] = [3, 3]


In [0]:
import tensorflow as tf


a = tf.placeholder(dtype=tf.int32, name='a')
b = tf.constant(1, name='b')
c = a + b

with tf.Session() as sess:
    print('a + b =', sess.run(c, feed_dict={a: 1}))

a + b = 2


In [0]:
import tensorflow as tf


a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
c = tf.add(a, b)  # a + b と等価
d = tf.multiply(a, b)  # a*b と等価

with tf.Session() as sess:
    print('a + b = ', sess.run(c))
    print('a * b = ', sess.run(d))

a + b =  5
a * b =  6


#陣列運算

In [0]:
import tensorflow as tf


a = tf.constant([1, 2, 3], name='a')
b = tf.constant([4, 5, 6], name='b')
c = a + b

with tf.Session() as sess:
    print('a + b = ', sess.run(c))

a + b =  [5 7 9]


#陣列運算

In [0]:
import tensorflow as tf


a = tf.constant([[1, 2], [3, 4]], name='a')
b = tf.constant([[1], [2]], name='b')
c = tf.matmul(a, b)

print('shape of a: ', a.shape)
print('shape of b: ', b.shape)
print('shape of c: ', c.shape)

with tf.Session() as sess:
    print('a = \n', sess.run(a))
    print('b = \n', sess.run(b))
    print('c = \n', sess.run(c))

shape of a:  (2, 2)
shape of b:  (2, 1)
shape of c:  (2, 1)
a = 
 [[1 2]
 [3 4]]
b = 
 [[1]
 [2]]
c = 
 [[ 5]
 [11]]


In [0]:
import tensorflow as tf

a = tf.placeholder(shape=(None, 2), dtype=tf.int32, name='a')

with tf.Session() as sess:
    print('-- 設定a=[[1, 2]] --')
    print('a = ', sess.run(a, feed_dict={a: [[1, 2]]}))
    
    print('\n-- 設定a=[[1, 2], [3, 4]] --')
    print('a = ', sess.run(a, feed_dict={a: [[1, 2], [3, 4]]}))

-- 設定a=[[1, 2]] --
a =  [[1 2]]

-- 設定a=[[1, 2], [3, 4]] --
a =  [[1 2]
 [3 4]]


In [0]:
import tensorflow as tf


a = tf.Variable(1, name='a')
b = tf.assign(a, a + 1)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('一回目 b = ', sess.run(b))
    print('二回目 b = ', sess.run(b))

# セッションが変わると元の値に戻ってしまう
with tf.Session() as sess:
    print('-- 新しいセッション --')
    sess.run(tf.global_variables_initializer())
    print('一回目 b = ', sess.run(b))
    print('二回目 b = ', sess.run(b))

一回目 b =  2
二回目 b =  3
-- 新しいセッション --
一回目 b =  2
二回目 b =  3
